---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu-desktop
  name: ubuntu-desktop
  namespace: desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-desktop
  template:
    metadata:
      labels:
        app: ubuntu-desktop
    spec:
      containers:
        #- image: jmcdice/k8s-ubuntu-desktop:latest
      - image: fredblgr/ubuntu-novnc:22.04
        imagePullPolicy: Always
        name: ubuntu-desktop
        ports:
        - containerPort: 6080
          protocol: TCP
        env:
        - name: VNC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vnc-password
              key: password
